name: flutter_portfolio
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  avatar_glow: ^1.0.0
  font_awesome_flutter: ^8.2.0
  preload_page_view: ^0.1.4
  url_launcher: ^5.2.5
  extended_image: ^0.6.5

dependency_overrides:
  extended_image_library:
    git:
      url: https://github.com/fluttercandies/extended_image_library.git
      ref: dev
  path_provider_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding/
      path: plugins/flutter_plugins/path_provider_fde
  url_launcher_fde:
    git:
      url: https://github.com/google/flutter-desktop-embedding/
      path: plugins/flutter_plugins/url_launcher_fde

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunitoSemiBold.ttf
        - asset: assets/fonts/nunitoBold.ttf
          weight: 700


  assets:
      - assets/images/avatar.png
      - assets/images/lucknow.png
      - assets/images/lucknow_heritage.png
      - assets/images/laptop.png
      - assets/images/mobile.png

      - assets/images/artist/i1.jpg
      - assets/images/artist/i2.jpg
      - assets/images/artist/i3.jpg
      - assets/images/artist/i4.jpg
      - assets/images/artist/i5.jpg
      - assets/images/pen.png
      - assets/images/plane_text.png
      - assets/images/unacademy.png
      - assets/images/unacademy/1.png
      - assets/images/unacademy/2.png
      - assets/images/unacademy/3.png
      - assets/images/unacademy/4.png

      - assets/images/intro/b2.jpg
      - assets/images/intro/footer.png

      - assets/images/about/lucknow.jpg

      - assets/images/education/roorkee.jpg

      - assets/images/work/workozy.png
      - assets/images/work/workozy_track.png
      - assets/images/work/office.jpg

      - assets/images/skills/bike.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
